# User keybind overrides
unbind = Super, F
bind = Super, F, exec, google-chrome-stable # Browser

unbind = Super, C
bind = Super, C, exec, antigravity-ide # Code editor

unbind = Super, X
bind = Super, X, exec, spotify # Spotify

unbind = Super, P
bindd = Super, P, Toggle wallpaper selector, global, quickshell:wallpaperSelectorToggle # Wallpaper selector
