-- Shell animation overrides (disabled)
hl.curve("pc_wobble", { type = "bezier", points = { {0.15, 1.15}, {0.35, 1.0}  } })
hl.curve("pc_decel",  { type = "bezier", points = { {0.05, 0.9},  {0.1,  1.05} } })
hl.curve("pc_accel",  { type = "bezier", points = { {0.3,  0},    {0.8,  0.15} } })
hl.animation({ leaf = "windowsIn",           enabled = false })
hl.animation({ leaf = "windowsOut",          enabled = false })
hl.animation({ leaf = "windowsMove",         enabled = false })
hl.animation({ leaf = "fadeIn",              enabled = false })
hl.animation({ leaf = "fadeOut",             enabled = false })
hl.animation({ leaf = "layersIn",            enabled = false })
hl.animation({ leaf = "layersOut",           enabled = false })
hl.animation({ leaf = "workspaces",          enabled = false })
hl.animation({ leaf = "specialWorkspaceIn",  enabled = false })
hl.animation({ leaf = "specialWorkspaceOut", enabled = false })
